{
 "title": "Prometheus Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GC pause duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "Quantile: {{quantile}}" }
   ]
  },
  {
   "title": "Requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(promhttp_metric_handler_requests_total[5m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Available target",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}