{
 "title": "Backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "Process" },
    { "expr": "system_cpu_usage", "legendFormat": "System" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "Rate" }
   ]
  },
  {
   "title": "CPU Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "Thread Type Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "Daemon" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live" },
    { "expr": "jvm_threads_peak_threads", "legendFormat": "Peak" }
   ]
  },
  {
   "title": "Thread States Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "State: {{state}}" }
   ]
  },
  {
   "title": "Thread Memory Eden",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"G1 Eden Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread Memory Survivor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Survivor Space\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"G1 Survivor Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread Memory Tenured",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Old Gen\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"G1 Old Gen\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Request Rate time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[30s]) / rate(http_server_requests_seconds_count[30s])",
     "legendFormat": "URL : {{uri}} ({{outcome}})"
    }
   ]
  },
  {
   "title": "GC collection time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{cause=\"G1 Evacuation Pause\"}"
    }
   ]
  },
  {
   "title": "Available target",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  }
 ]
}