global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitoring-instances'
      send_resolved: true