POST http://localhost:8080/api/bookings
Content-Type: application/json

{
  "travelId": 1,
  "bookingPassengerId": 71,
  "stationA": "StopPoint:OCETGV INOUI-87391003",
  "stationB": "StopPoint:OCETGV INOUI-87484006",
  "date": "2020-01-11",
  "seatBookingRequests": [
    {
      "seatId": 2,
      "firstName": "Emmanuel",
      "lastName": "Macron",
      "birthdate": "21/12/1977",
      "email": "emacron@fakehost.ru",
      "phoneNumber": "0123456789"
    },
    {
      "seatId": 4,
      "firstName": "Brigitte",
      "lastName": "Macron",
      "birthdate": "13/04/1953",
      "email": "emacron@fakehost.ru",
      "phoneNumber": "0123456789"
    },
    {
      "seatId": 5,
      "firstName": "Mélissa",
      "lastName": "Russo",
      "birthdate": "26-01-1999",
      "email": "lacus.Quisque@elementumloremut.com",
      "phoneNumber": "07 67 98 19 55"
    },
    {
      "seatId": 9,
      "firstName": "Henri",
      "lastName": "Russo",
      "birthdate": "26-01-1999",
      "email": "lacus.Quisque@elementumloremut.com",
      "phoneNumber": "07 67 98 19 55"
    },
    {
      "seatId": 14,
      "firstName": "Mélissa",
      "lastName": "Toriot",
      "birthdate": "26-01-1999",
      "email": "lacus.Quisque@elementumloremut.com",
      "phoneNumber": "07 67 98 19 55"
    },
    {
      "seatId": 13,
      "firstName": "Rufus",
      "lastName": "Russo",
      "birthdate": "26-01-1999",
      "email": "lacus.Quisque@elementumloremut.com",
      "phoneNumber": "07 67 98 19 55"
    },
    {
      "seatId": 12,
      "firstName": "TOM",
      "lastName": "Russo",
      "birthdate": "26-01-1999",
      "email": "lacus@elementumloremut.com",
      "phoneNumber": "07 67 98 19 55"
    },
    {
      "seatId": 11,
      "firstName": "Mélissa",
      "lastName": "Russo",
      "birthdate": "26-02-1999",
      "email": "lacus.Quisque@elementumemut.com",
      "phoneNumber": "07 67 98 19 55"
    },
    {
      "seatId": 15,
      "firstName": "Mélissa",
      "lastName": "Russo",
      "birthdate": "26-01-1899",
      "email": "lacus.Quisque@elementumloremut.com",
      "phoneNumber": "07 67 98 19 55"
    }
  ]
}

##### RESPONSE
#{
#  "invoiceLink": "invoicelink0",
#  "bookingNumber": "dd023a020f",
#  "ticketLinks": [
#    "31335dd048f5460c",
#    "d347eab8bb984719",
#    "dh890a68bb984718"
#  ]
#}
